spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_list_prod
    username: root
    password: Bazadanych2002!
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: update