spring:
  datasource:
    url: jdbc:h2:mem:test
  #    url: jdbc:mysql://localhost:3306/todo_list_dev
#    username: root
#    password: Bazadanych2002!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  liquibase:
    change-log: classpath:db/changelog/master.xml
#    enabled: false